---
title: "Untitled"
output: word_document
date: "2024-11-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE)
```

  
```{r}
library(Rchoice)

n <- 10000  # number of observations
lambda_true <- -7  # true mean count

# Generate random parameters for each observation
random_params <- rnorm(n, mean = -2, sd = 3)
x1 <- rnorm(n, mean = 1, sd = 2)  # Continuous variable
x2 <- runif(n, min=1, max = 2)  # Continuous variable
#x2 <- sample(0:1, n, replace = TRUE)  # Binary variable


# Generate count data from a Poisson distribution
counts <- rpois(n, lambda = exp(lambda_true + x1*1+x2*random_params))



# Create a data frame
data <- data.frame(counts = counts, x1 = x1, x2 = x2)

```
  
---

```{r}
a = Rchoice(counts ~ x1 +x2, data = data, ranp = c(x2 = "n"), family = poisson, R = 200, init.ran = 3, start = c(-7, .5, -1, 3))
c = Rchoice(counts ~ x1 +x2, data = data, ranp = c(x2 = "u"), family = poisson, R = 200, init.ran = 3, start = c(-7, .5, -1, 3))
d = Rchoice(counts ~ x1 +x2, data = data, ranp = c(x2 = "t"), family = poisson, R = 200, init.ran = 3, start = c(-7, .5, -1, 3))

```



```{r}
b = Rchoice(counts ~ x1 +x2, data = data, family = poisson, start = c(-7, .5, -5))
summary(b)
```



#summary(b)
#summary(a)



# Extract coefficients
#constant <- -7.011510
#coef_x1 <- 0.955229
#mean_x2 <- -0.982689
#sd_x2 <- 3.003342



```{r}
library("memisc")
Ttable <- mtable("model 1"= a, "model 2" = b, summary.stats = c("N", "Log-likelihood", "BIC", "AIC"))
Ttable
```


```{r}
Ttableb <- mtable("model n"= a, "model u" = c, "model t" = d, summary.stats = c("N", "Log-likelihood", "BIC", "AIC"))
Ttableb
```


