"""Auto-generated by ModelZoo GUI — CMF (JAX flexible search) run: CMF_Washington

Run locally:
    python hs_run_cmf.py

Uses CMFExperimentBuilder.build_jax_count_evaluator(), which bridges the
AADT baseline/local-interaction structure into a regular ExperimentBuilder
evaluator -- this is the route that supports full ModelConstraints
(force_include/force_fixed/exclude/mutual_exclusion/...) and latent classes.
"""
import os
import sys
os.environ.setdefault("JAX_PLATFORMS", "cpu")
sys.stdout.reconfigure(encoding="utf-8", errors="replace")
sys.stderr.reconfigure(encoding="utf-8", errors="replace")

import time
from pathlib import Path
import pandas as pd
from metacountregressor import (
    CMFExperimentBuilder,
    ModelConstraints,
    SearchOutputConfig,
    extract_search_best,
    extract_summary,
    compare_models,
)

print("=" * 70)
print("CMF (JAX flexible search) run: CMF_Washington")
print("=" * 70)

t0 = time.time()
df = pd.read_csv('Ex-16-3.csv')
print(f"Loaded data: {df.shape[0]} rows x {df.shape[1]} cols")

constraints = (
    ModelConstraints()
)
print(constraints)

cmf = CMFExperimentBuilder(
    df=df,
    y_col='FREQ',
    aadt_col='AADT',
    baseline_vars=["SPEED", "WIDTH", "CURVES", "MINRAD", "ACCESS", "GRADEBR","FRICTION", "SINGLE", "TANGENT", "SLOPE","GBRPM", "INTPM", "CPM", "MEDWIDTH", "INCLANES","DOUBLE", "TRAIN", "PEAKHR"],
    local_vars=[ 'EXPOSE', "WIDTH", "CURVES", "GRADEBR", "MEDWIDTH"]
)

builder, evaluator, metadata = cmf.build_jax_count_evaluator(
    id_col='ID',
    offset_col='OFFSET',
    variables=[],
    constraints=constraints,
    max_latent_classes=1,
    R=200,
    default_roles=[0, 1, 2, 3, 5],
    force_aadt_term=True,
)
print("CMF term map (baseline/local -> internal names):", metadata["term_map"])

output_config = SearchOutputConfig(
    output_dir='results',
    experiment_name='CMF_Washington',
    search_description='First_Test_Run',
    save_json=True,
)

print("\nRunning search (algo='sa')...")
result = builder.run(
    evaluator,
    algo='hs',
    max_iter=1750,
    seed=42,
    output_config=output_config,
)

elapsed = time.time() - t0
best = extract_search_best(result)
print(f"\nSearch finished in {elapsed:.1f}s")
print("Best BIC:", best["best_bic"])
print("Saved to:", result.get("saved_to"))

out_dir = Path('results')
out_dir.mkdir(parents=True, exist_ok=True)

if best.get("best_decision") is None:
    raise RuntimeError(
        "Search returned no best_decision (best_bic="
        f"{best.get('best_bic')!r}). The raw population/scores were "
        f"already saved to {result.get('saved_to')!r} by builder.run(), "
        "so the search itself is not lost -- but there is no single best "
        "structure to refit here. This should no longer happen after the "
        "metacountregressor fix to ExperimentBuilder.run()'s hs/de branch; "
        "if it recurs, inspect the saved population file directly."
    )

best_spec = evaluator.build_spec(best["best_decision"])

# Persist the best structure immediately, before attempting the (separate,
# potentially fragile) per-family refits below -- a multi-hour search's
# result should not be lost to a downstream refit crash. This mirrors what
# ExperimentBuilder.run() itself now saves via save_run_summary_to_txt(),
# but keeps a plain JSON copy here too since best_spec is what this
# script's own downstream steps (and any manual re-run) actually consume.
import json as _json
with open(out_dir / "CMF_Washington_best_spec.json", "w") as _f:
    _json.dump(best_spec, _f, indent=2, default=str)
print(f"Best structure spec saved to: {out_dir / 'CMF_Washington_best_spec.json'}")

fit_families = ['nb', 'poisson']
fits = {}
for family in fit_families:
    print(f"\nRefitting best structure as {family!r} with R=500...")
    try:
        fits[family] = builder.fit_manual_model(manual_spec=best_spec, model=family, R=500)
    except Exception as exc:
        print(f"  [warn] Refit as {family!r} failed: {exc}")
        print(f"  (best_spec is still saved at {out_dir / 'CMF_Washington_best_spec.json'} "
              f"and can be refit manually)")
        continue
    summary = extract_summary(fits[family])
    print(f"  {family} summary:")
    for k, v in summary.items():
        print(f"    {k:>10}: {v}")

if len(fits) > 1:
    print("\nModel family comparison (sorted by BIC):")
    comparison = compare_models(fits)
    print(comparison.to_string(index=False))
    comparison.to_csv(out_dir / ('CMF_Washington' + "_family_comparison.csv"), index=False)
elif len(fits) == 1:
    print(f"\nOnly one family ({list(fits)[0]!r}) fit successfully; skipping comparison.")
