<!DOCTYPE html>
<html lang="en"><head>
<script src="cmf_technical_slides_clean - new_files/libs/clipboard/clipboard.min.js"></script>
<script src="cmf_technical_slides_clean - new_files/libs/quarto-html/tabby.min.js"></script>
<script src="cmf_technical_slides_clean - new_files/libs/quarto-html/popper.min.js"></script>
<script src="cmf_technical_slides_clean - new_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="cmf_technical_slides_clean - new_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="cmf_technical_slides_clean - new_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="cmf_technical_slides_clean - new_files/libs/quarto-html/quarto-syntax-highlighting-e1a5c8363afafaef2c763b6775fbf3ca.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.31">

  <meta name="author" content="Traffic Safety Analysis">
  <meta name="dcterms.date" content="2026-04-23">
  <title>Crash Modification Factors</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="cmf_technical_slides_clean - new_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="cmf_technical_slides_clean - new_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="cmf_technical_slides_clean - new_files/libs/revealjs/dist/theme/quarto-2c1b5f745a11cfad616ebade4a4a7d24.css">
  <link href="cmf_technical_slides_clean - new_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="cmf_technical_slides_clean - new_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="cmf_technical_slides_clean - new_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="cmf_technical_slides_clean - new_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <style>
    .reveal .slides section { font-size: 0.84em; }
    .reveal .slides section.compact { font-size: 0.76em; }
    .reveal .slides mjx-container { max-width: 100%; }
    .reveal .slides mjx-container[display="true"] {
      margin: 0.2em auto !important;
      font-size: 0.92em !important;
    }
    .reveal .slides section.compact mjx-container[display="true"] {
      font-size: 0.84em !important;
    }
    .reveal table { font-size: 0.64em; }
    .reveal pre code { font-size: 0.70em; line-height: 1.25; }
    .reveal p, .reveal li { line-height: 1.28; }
    .model-trad { color: #1f77b4; font-weight: 700; }
    .model-cmf { color: #2e8b57; font-weight: 700; }
    .coef-pos { color: #b22222; font-weight: 700; }
    .coef-neg { color: #1b5e20; font-weight: 700; }
    .delta-neg { color: #6a1b9a; font-weight: 700; }
    .chip {
      display: inline-block;
      padding: 2px 8px;
      border-radius: 10px;
      font-size: 0.85em;
      background: #f4f6f8;
      border: 1px solid #d9dee3;
    }
    .legend-fixed {
      position: fixed;
      top: 8px;
      right: 10px;
      z-index: 30;
      font-size: 12px;
      background: rgba(255, 255, 255, 0.92);
      border: 1px solid #d9dee3;
      border-radius: 999px;
      padding: 4px 10px;
      box-shadow: 0 1px 3px rgba(0,0,0,0.08);
    }
    .legend-fixed .legend-sep {
      color: #8a8f98;
      padding: 0 6px;
    }
  </style>
  <script>
    document.addEventListener('DOMContentLoaded', function () {
      if (document.querySelector('.legend-fixed')) return;

      const legend = document.createElement('div');
      legend.className = 'legend-fixed';
      legend.id = 'model-legend-fixed';
      legend.innerHTML =
        '<span class="model-trad">Traditional</span>' +
        '<span class="legend-sep">|</span>' +
        '<span class="model-cmf">CMF</span>';
      document.body.appendChild(legend);

      function shouldHideLegend(slideEl) {
        if (!slideEl) return false;
        if (slideEl.classList.contains('title-slide')) return true;

        const heading = slideEl.querySelector('h1, h2, h3');
        if (!heading) return false;
        const title = (heading.textContent || '').trim().toLowerCase();
        return (
          title.startsWith('references') ||
          title.includes('appendix') ||
          title.includes('backup')
        );
      }

      function updateLegendVisibility() {
        const el = document.getElementById('model-legend-fixed');
        if (!el) return;

        if (window.Reveal && typeof window.Reveal.getCurrentSlide === 'function') {
          const current = window.Reveal.getCurrentSlide();
          el.style.display = shouldHideLegend(current) ? 'none' : 'block';
        } else {
          el.style.display = 'block';
        }
      }

      updateLegendVisibility();

      if (window.Reveal && typeof window.Reveal.on === 'function') {
        window.Reveal.on('ready', updateLegendVisibility);
        window.Reveal.on('slidechanged', updateLegendVisibility);
      }
    });
  </script>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Crash Modification Factors</h1>
  <p class="subtitle">Hierarchical Count Modeling for Road Safety</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Traffic Safety Analysis 
</div>
</div>
</div>

  <p class="date">2026-04-23</p>
</section>
<section id="motivation" class="slide level2 compact">
<h2>Motivation</h2>
<p>When engineers face a design decision:</p>
<ul>
<li>Should we widen lanes?</li>
<li>Should we reduce curves?</li>
<li>Should we change shoulder width?</li>
</ul>
<p>We need to answer:</p>
<blockquote>
<p><strong>How much will crashes change if we implement a treatment?</strong></p>
</blockquote>
<p>That is exactly what a Crash Modification Factor (CMF) provides.</p>
<p>CMFs translate model coefficients into:</p>
<ul>
<li>Percent crash change</li>
<li>Decision-ready safety impacts</li>
<li>Policy-relevant safety tradeoffs</li>
</ul>
</section>
<section id="what-a-cmf-actually-does" class="slide level2 compact">
<h2>What a CMF Actually Does</h2>
<p>A CMF answers one question:</p>
<blockquote>
<p>If we change a road feature from condition A to condition B how will predicted crashes change?</p>
</blockquote>
<p>Example:</p>
<ul>
<li>Lane width = 1.8 m → 2 m</li>
<li>Curve density = 2 → 3 per km</li>
<li>Shoulder width = .6 m → 1 m</li>
</ul>
<p>The CMF tells us:</p>
<ul>
<li>0.85 → 15% crash reduction</li>
<li>1.10 → 10% crash increase</li>
</ul>
</section>
<section id="what-are-crash-modification-factors" class="slide level2 compact">
<h2>What Are Crash Modification Factors?</h2>
<p><strong>CMF Definition:</strong></p>
<p><span class="math display">\[\text{CMF}(a \rightarrow b) = \frac{\hat{N}_b}{\hat{N}_a}\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(a\)</span> = the current condition a.</li>
<li><span class="math inline">\(b\)</span> = after a treatment/change</li>
<li><span class="math inline">\(\hat{N}_a\)</span> = predicted crashes in condition <span class="math inline">\(a\)</span></li>
<li><span class="math inline">\(\hat{N}_b\)</span> = predicted crashes in condition <span class="math inline">\(b\)</span></li>
</ul>
<p>Why CMF changes:</p>
<ul>
<li>If the treatment lowers predicted crashes (<span class="math inline">\(\hat{N}_b &lt; \hat{N}_a\)</span>), then CMF &lt; 1.</li>
<li>If the treatment raises predicted crashes (<span class="math inline">\(\hat{N}_b &gt; \hat{N}_a\)</span>), then CMF &gt; 1.</li>
</ul>
</section>
<section class="slide level2">

<p>**Example: Increase Width increases by 1 w</p>
<p>with <span class="math inline">\(\beta_{WIDTH}=-0.08394\)</span>**</p>
<p><span class="math display">\[
\begin{aligned}
\Delta \log(\hat N) &amp;= -0.08394 \times 1 = -0.08394 \\
CMF &amp;= \exp(-0.08394) = 0.9195 \\
\%\text{ change} &amp;= 100\,(0.9195 - 1) = -8.05\%
\end{aligned}
\]</span></p>
<ul>
<li>If the exponent is negative, then <span class="math inline">\(CMF &lt; 1\)</span> and crashes go down.</li>
<li>If the exponent is positive, then <span class="math inline">\(CMF &gt; 1\)</span> and crashes go up.</li>
</ul>
</section>
<section id="conceptual-structure" class="slide level2 compact">
<h2>Conceptual Structure</h2>
<h3 id="traditional-model">Traditional Model</h3>
<p><span class="math display">\[
\log(\hat N_i) = \text{Single additive equation}
\]</span></p>
<p>That is</p>
<p><span class="math display">\[\hat{N}_i = E_i \times \exp(\beta_0 + \beta_1 X_{1i} + \beta_2 X_{2i} + \ldots)\]</span></p>
<p>Everything is estimated together:</p>
<ul>
<li>Crash propensity<br>
</li>
<li>Traffic exposure<br>
</li>
<li>Traffic elasticity<br>
</li>
<li>Geometry effects</li>
</ul>
</section>
<section class="slide level2">

<h3 id="hierarchical-cmf-model">Hierarchical CMF Model</h3>
<p><span class="math display">\[
\hat N_i =
\underbrace{\exp(\text{baseline features})}_{\textbf{Inherent Risk}}
\times
\underbrace{AADT^{(\text{elasticity modified by geometry})}}_{\textbf{Traffic Response}}
\]</span></p>
<p>Two distinct mechanisms:</p>
<ul>
<li><strong>Baseline block</strong> -&gt; inherent crash propensity</li>
<li><strong>Traffic-response block</strong> -&gt; how crashes scale with traffic</li>
</ul>
<p>This structural separation is the key advantage: AADT response is modeled explicitly.</p>
<blockquote>
<p>Traditional models usually treat AADT primarily through exposure, not as a separate mechanism.</p>
</blockquote>
</section>
<section id="what-the-exposure-offset-really-does" class="slide level2 compact">
<h2>What the Exposure (Offset) Really Does</h2>
<p>Traditional model with exposure:</p>
<p><span class="math display">\[
\hat N_i = E_i \times \exp(\beta_0 + \beta_1 X_{1i} + \dots)
\]</span></p>
<p>If we assume AADT multiplied by segment length is the exposure:</p>
<p><span class="math display">\[
E_i = AADT_i \times LENGTH_i
\]</span></p>
<p>Then:</p>
<p><span class="math display">\[
\log(\hat N_i) =
\log(AADT_i) + \log(LENGTH_i) + \text{linear predictor}
\]</span></p>
<h3 id="important">Important</h3>
<p>Including AADT in the offset:</p>
<ul>
<li>Traffic elasticity remains fixed</li>
<li>Assumes proportional exposure</li>
<li>Makes it harder for geometry to directly modify traffic scaling</li>
</ul>
<p>It assumes:</p>
<blockquote>
<p>If traffic doubles, crashes double — regardless of geometry. Treatments are likely to cause changes in traffic</p>
</blockquote>
</section>

<section id="what-the-hierarchical-cmf-structure-allows" class="slide level2 compact">
<h2>What the Hierarchical CMF Structure Allows</h2>
<p>Baseline block:</p>
<p><span class="math display">\[
\hat N_i^{\text{baseline}}
=
\exp(\alpha_0 + \alpha_1 X_{1i} + \dots)
\]</span></p>
<p>Traffic-response block:</p>
<p><span class="math display">\[
\hat N_i
=
\hat N_i^{\text{baseline}}
\times
AADT_i^{(\gamma_0 + \gamma_1 \text{WIDTH}_i + \gamma_2 \text{CURVES}_i)}
\]</span></p>
<p>Now geometry can:</p>
<ul>
<li>Affect inherent crash risk through the baseline channel</li>
<li>Independently modify traffic elasticity</li>
</ul>
<blockquote>
<p>Traffic scaling becomes geometry-dependent. For example, changes in WIDTH and CURVES can directly adjust AADT response.</p>
</blockquote>
</section>
<section id="the-problem-traditional-models" class="slide level2 compact">
<h2>The Problem: Traditional Models</h2>
<p>Traditional negative binomial regression:</p>
<p><span class="math display">\[\hat{N}_i = E_i \times \exp(\beta_0 + \beta_1 X_{1i} + \beta_2 X_{2i} + \ldots)\]</span></p>
<h3 id="three-critical-questions">Three Critical Questions</h3>
<ol type="1">
<li><strong>What causes the coefficient?</strong>
<ul>
<li>Does CURVES increase crashes directly?</li>
<li>Or does it reflect traffic volume confounding (AADT)?</li>
</ul></li>
<li><strong>How do we design interventions?</strong>
<ul>
<li>Should we prioritize geometry changes or traffic management?</li>
<li>Are both quantified?</li>
</ul></li>
<li><strong>What if exposure assumptions are wrong?</strong>
<ul>
<li>Exposure effect should account for differences in road segmentation</li>
<li>But maybe longer roads have different safety dynamics</li>
</ul></li>
</ol>
</section>
<section id="solution-hierarchical-cmf-model" class="slide level2 compact">
<h2>Solution: Hierarchical CMF Model</h2>
<h3 id="two-level-structure">Two-Level Structure</h3>
<p><strong>Level 1 — Baseline Block</strong> (inherent crash propensity): <span class="math display">\[\hat{N}_i^{\text{baseline}} = \exp(\alpha_0 + \alpha_{\text{URB}} \cdot \text{URB}_i + \alpha_{\text{ACCESS}} \cdot \text{ACCESS}_i + \cdots)\]</span></p>
<p><strong>Level 2 — Traffic-Response Block</strong> (AADT elasticity): <span class="math display">\[\hat{N}_i = \hat{N}_i^{\text{baseline}} \times \text{AADT}_i^{(\gamma_0 + \gamma_{\text{WIDTH}} \cdot \text{WIDTH}_i + \cdots)}\]</span></p>
<h3 id="key-advantage">Key Advantage</h3>
<ul>
<li><strong>Baseline features</strong> (URB, ACCESS, …) → What geometric factors directly explain the crash process</li>
<li><strong>AADT features</strong> (WIDTH, CURVES, …) → How does the geometric factors affect the traffic volume sensitivity change?</li>
</ul>
</section>
<section id="experiment-setup" class="slide level2 compact">
<h2>Experiment Setup</h2>
<h3 id="washington-rural-roads-from-1990">Washington Rural Roads from 1990</h3>
<ul>
<li><strong>Dataset:</strong> 275 road segments, 4-year crashes</li>
<li><strong>Median AADT:</strong> 23,771 vehicles/day</li>
<li><strong>Variables used:</strong> URB, ACCESS, GRADEBR, CURVES, WIDTH, AADT, LENGTH</li>
</ul>
<h3 id="comparison-design">Comparison Design</h3>
<ol type="1">
<li>Traditional NB model and Hierarchical CMF model are fit on the same data.</li>
<li>Both models include CURVES and WIDTH explicitly.</li>
<li>Observe the interpretation quality for treatment planning.</li>
</ol>
</section>
<section class="slide level2">

</section>
<section id="fit-quality" class="slide level2 compact">
<h2>Fit Quality</h2>
<table class="caption-top">
<colgroup>
<col style="width: 22%">
<col style="width: 33%">
<col style="width: 13%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>Traditional</th>
<th>CMF</th>
<th>Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>BIC</strong></td>
<td>1925.52</td>
<td>1931.82</td>
<td>+6.3</td>
</tr>
<tr class="even">
<td><strong>Deviance</strong></td>
<td>210.45</td>
<td>208.12</td>
<td>-2.33</td>
</tr>
<tr class="odd">
<td><strong>Interpretability</strong></td>
<td>Elasticity Fixed</td>
<td>Traffic related and Geometric Elasticity</td>
<td></td>
</tr>
</tbody>
</table>
<p><strong>Conclusion:</strong> You sacrifice <strong>6.3 BIC points</strong> to gain <strong>mechanistic clarity</strong> and <strong>better interpretability</strong>.</p>
</section>

<section id="fitted-traditional-model" class="slide level2 compact">
<h2>Fitted Traditional Model</h2>
<p><span class="chip model-trad">Traditional NB model</span></p>
<p><strong>Structural form</strong></p>
<p><span class="math display">\[
\begin{aligned}
\log(\hat{N}_i) = \beta_0
  + \beta_1\,URB
  + \beta_2\,ACCESS
  + \beta_3\,GRADEBR
  + \beta_4\,CURVES\\
  + \beta_5\,WIDTH
  + \beta_6\,\log(AADT_i)
  + \log(LENGTH_i)
\end{aligned}
\]</span></p>
<p><strong>Fitted coefficients</strong></p>
<p><span class="math display">\[
\begin{aligned}
\log(\hat{N}_i) = 1.794
  + 0.179\,URB
  + 0.241\,ACCESS
  + 0.063\,GRADEBR
  + 0.056\,CURVES \\
  - 0.065\,WIDTH
  + 0.590\,\log(AADT_i)
  + \log(LENGTH_i)
\end{aligned}
\]</span></p>
</section>
<section id="how-one-coefficient-becomes-a-cmf-traditional" class="slide level2 compact">
<h2>How one coefficient becomes a CMF Traditional</h2>
<p><span class="math display">\[
\begin{aligned}
\log\!\left(\frac{\hat N_{after}}{\hat N_{before}}\right) &amp;= \beta_j\,\Delta x_j \\
CMF &amp;= \exp\!\left(\beta_j\,\Delta x_j\right) \\
\%\text{ change} &amp;= 100\,\left[\exp\!\left(\beta_j\,\Delta x_j\right) - 1\right]
\end{aligned}
\]</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Parameter</th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Effect for <span class="math inline">\(+1\)</span> unit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>URB</td>
<td style="text-align: right;"><span class="coef-pos">+0.179</span></td>
<td style="text-align: right;">+19.6%</td>
</tr>
<tr class="even">
<td>ACCESS</td>
<td style="text-align: right;"><span class="coef-pos">+0.241</span></td>
<td style="text-align: right;">+27.3%</td>
</tr>
<tr class="odd">
<td>GRADEBR</td>
<td style="text-align: right;"><span class="coef-pos">+0.063</span></td>
<td style="text-align: right;">+6.5%</td>
</tr>
<tr class="even">
<td>CURVES</td>
<td style="text-align: right;"><span class="coef-pos">+0.056</span></td>
<td style="text-align: right;">+5.8%</td>
</tr>
<tr class="odd">
<td>WIDTH</td>
<td style="text-align: right;"><span class="coef-neg">-0.065</span></td>
<td style="text-align: right;">-6.3%</td>
</tr>
<tr class="even">
<td>AADT</td>
<td style="text-align: right;"><span class="coef-pos">+0.590</span></td>
<td style="text-align: right;">+80.3%</td>
</tr>
</tbody>
</table>
<p><strong>Key point:</strong> every treatment has one pooled slope, so the treatment effect is constant across all traffic levels.</p>
</section>
<section id="fitted-hierarchical-cmf-model" class="slide level2 compact">
<h2>Fitted Hierarchical CMF Model</h2>
<p><span class="chip model-cmf">Hierarchical CMF model</span></p>
<p><strong>Structural form</strong></p>
<p><span class="math display">\[
\log(\hat{N}_i) = \log(L_i)
  + \underbrace{\left(\alpha_0 + \boldsymbol{\alpha}^\top\mathbf{x}_i\right)}_{\text{baseline block}}
  + \underbrace{\left(\gamma_0 + \boldsymbol{\gamma}^\top\mathbf{z}_i\right)\log(AADT_i)}_{\text{traffic-response block}}
\]</span></p>
<p><strong>Fitted coefficients</strong></p>
<p><span class="math display">\[
\begin{aligned}
\log(\hat{N}_i) = {} &amp; \log(L_i) \\
&amp; + \underbrace{\left(-6.394 - 0.020\,URB + 0.141\,ACCESS + 0.097\,GRADEBR - 0.993\,CURVES - 1.947\,WIDTH\right)}_{\text{baseline block}} \\
&amp; + \underbrace{\left(0.812 + 0.123\,CURVES + 0.175\,WIDTH\right)\,\log(AADT_i)}_{\text{traffic-response block}}
\end{aligned}
\]</span></p>
</section>
<section id="how-coefficients-become-cmfs-hierarchical" class="slide level2 compact">
<h2>How coefficients become CMFs Hierarchical</h2>
<p>For a treatment that appears <strong>only in the baseline block</strong>:</p>
<p><span class="math display">\[
\begin{aligned}
\log\!\left(\frac{\hat N_{after}}{\hat N_{before}}\right) &amp;= \alpha_j\,\Delta x_j \\
CMF &amp;= \exp\!\left(\alpha_j\,\Delta x_j\right)
\end{aligned}
\]</span></p>
<p>For a treatment that also changes the <strong>traffic-response block</strong>:</p>
<p><span class="math display">\[
\begin{aligned}
\log\!\left(\frac{\hat N_{after}}{\hat N_{before}}\right) &amp;= \left(\alpha_j + \gamma_j\log(AADT)\right)\,\Delta x_j \\
CMF(AADT) &amp;= \exp\!\left[\left(\alpha_j + \gamma_j\log(AADT)\right)\,\Delta x_j\right]
\end{aligned}
\]</span></p>
</section>
<section class="slide level2">

<table class="caption-top">
<colgroup>
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 30%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Block</th>
<th>Parameter</th>
<th style="text-align: right;">Estimate</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Baseline</td>
<td>CURVES</td>
<td style="text-align: right;"><span class="coef-neg">-0.993</span></td>
<td>road geometry shifts inherent crash risk</td>
</tr>
<tr class="even">
<td>Baseline</td>
<td>WIDTH</td>
<td style="text-align: right;"><span class="coef-neg">-1.947</span></td>
<td>road width shifts inherent crash risk</td>
</tr>
<tr class="odd">
<td>Traffic-response</td>
<td><span class="math inline">\(\gamma_0\)</span> (base elasticity)</td>
<td style="text-align: right;"><span class="coef-pos">+0.812</span></td>
<td>how crashes scale with traffic in general</td>
</tr>
<tr class="even">
<td>Traffic-response</td>
<td>CURVES <span class="math inline">\(\times\)</span> log(AADT)</td>
<td style="text-align: right;"><span class="coef-pos">+0.123</span></td>
<td>curvy roads attract more crashes as traffic grows</td>
</tr>
<tr class="odd">
<td>Traffic-response</td>
<td>WIDTH <span class="math inline">\(\times\)</span> log(AADT)</td>
<td style="text-align: right;"><span class="coef-pos">+0.175</span></td>
<td>wider roads attract more crashes as traffic grows</td>
</tr>
</tbody>
</table>
<p><strong>Key point:</strong> the CMF treatment effect can change through two channels: a baseline shift and a traffic-sensitivity shift.</p>
</section>



<section id="what-is-changing" class="slide level2 compact">
<h2>What is changing?</h2>
<ul>
<li>Traditional: only the fixed WIDTH slope <span class="math inline">\(\beta_{WIDTH}\)</span> changes the prediction ratio.</li>
<li>CMF: the WIDTH effect is recalculated at each AADT because both baseline and traffic-response matter.</li>
</ul>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>AADT Level</th>
<th style="text-align: right;"><span class="math inline">\(-1.947 + 0.175\,\log(AADT)\)</span></th>
<th style="text-align: right;">CMF</th>
<th style="text-align: right;">% Change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10,000</td>
<td style="text-align: right;"><span class="math inline">\(-1.947 + 0.175\times 9.21 = -0.335\)</span></td>
<td style="text-align: right;">0.715</td>
<td style="text-align: right;">-28.5%</td>
</tr>
<tr class="even">
<td>23,771 (median)</td>
<td style="text-align: right;"><span class="math inline">\(-1.947 + 0.175\times 10.08 = -0.185\)</span></td>
<td style="text-align: right;">0.831</td>
<td style="text-align: right;">-16.8%</td>
</tr>
<tr class="odd">
<td>60,000</td>
<td style="text-align: right;"><span class="math inline">\(-1.947 + 0.175\times 11.00 = -0.022\)</span></td>
<td style="text-align: right;">0.978</td>
<td style="text-align: right;">-2.2%</td>
</tr>
</tbody>
</table>
<p><strong>Interpretation:</strong> Traditional gives one average effect; CMF gives traffic-specific effects.</p>
<blockquote>
<p>Increasing width also increasing traffic sentitivity as this is likely to cause more traffic to use the road, which is a different mechanism than the baseline effect of width on inherent crash risk.</p>
</blockquote>
</section>
<section id="curves-treatment-traditional-vs-cmf" class="slide level2 compact">
<h2>CURVES Treatment: Traditional vs CMF</h2>
<p><strong>Intervention:</strong> reduce CURVES by <span class="math inline">\(-1\)</span>.</p>
<h3 id="traditional-fitted-formula-1">Traditional — fitted formula</h3>
<p><span class="math display">\[
CMF = \exp\!\bigl(\beta_{CURVES}\cdot\Delta CURVES\bigr) = \exp(0.056 \times -1) = 0.946 \quad\Rightarrow\quad -5.4\%
\]</span></p>
<p>(same regardless of AADT)</p>
<h3 id="cmf-fitted-formula-1">CMF — fitted formula</h3>
<p><span class="math display">\[
\begin{aligned}
CMF(AADT) &amp;= \exp\!\Bigl[\bigl(\alpha_{CURVES} + \gamma_{CURVES}\,\log(AADT)\bigr)\times(-1)\Bigr] \\
&amp;= \exp\!\Bigl[0.993 - 0.123\,\log(AADT)\Bigr]
\end{aligned}
\]</span></p>
</section>
<section id="what-is-changing-conceptually" class="slide level2 compact">
<h2>What is changing conceptually?</h2>
<ul>
<li>Traditional: reducing CURVES moves one pooled slope, so every corridor gets the same estimated reduction.</li>
<li>CMF: reducing CURVES changes both the baseline term and the traffic-scaling term, so higher AADT corridors get a larger estimated benefit.</li>
</ul>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>AADT Level</th>
<th style="text-align: right;"><span class="math inline">\(0.993 - 0.123\,\log(AADT)\)</span></th>
<th style="text-align: right;">CMF</th>
<th style="text-align: right;">% Change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10,000</td>
<td style="text-align: right;"><span class="math inline">\(0.993 - 0.123\times 9.21 = -0.140\)</span></td>
<td style="text-align: right;">0.869</td>
<td style="text-align: right;">-13.1%</td>
</tr>
<tr class="even">
<td>23,771 (median)</td>
<td style="text-align: right;"><span class="math inline">\(0.993 - 0.123\times 10.08 = -0.247\)</span></td>
<td style="text-align: right;">0.781</td>
<td style="text-align: right;">-22.0%</td>
</tr>
<tr class="odd">
<td>60,000</td>
<td style="text-align: right;"><span class="math inline">\(0.993 - 0.123\times 11.00 = -0.360\)</span></td>
<td style="text-align: right;">0.698</td>
<td style="text-align: right;">-30.3%</td>
</tr>
</tbody>
</table>
<p><strong>Interpretation:</strong> both models suggest fewer curves reduce crashes, but only CMF changes the size of that reduction with traffic level.</p>
<blockquote>
<p>Reducing curves has a bigger impact on higher-traffic roads because it improves traffic flow and reduces conflict points, which is captured by the traffic-response block in the CMF model.</p>
</blockquote>
</section>
<section id="traditional-vs-cmf-practical-narrative" class="slide level2 compact">
<h2>Traditional vs CMF: Practical Narrative</h2>
<p>What traditional NB is doing:</p>
<ul>
<li>One effect per treatment variable.</li>
<li>Easy to summarise, but it pools all segments into one treatment slope and cannot observe what the intended affect will result on traffic.</li>
</ul>
<p>What hierarchical CMF is doing:</p>
<ul>
<li>Baseline channel for general treatment effects.</li>
<li>AADT-response channel for traffic-conditioned treatment effects.</li>
<li>Better for deciding where a treatment should be prioritised.</li>
</ul>
</section>
<section id="final-takeaway" class="slide level2 compact">
<h2>Final Takeaway</h2>
<p>CMF can be applied in two distinct ways:</p>
<ol type="1">
<li><strong>General treatments:</strong> baseline CMFs (traffic level not required).</li>
<li><strong>AADT-sensitive treatments:</strong> CMFs computed at chosen traffic levels.</li>
</ol>
<p>That is the key modeling difference versus traditional NB regression:</p>
<ul>
<li>Traditional usually reports one pooled treatment effect.</li>
<li>CMF separates baseline risk from traffic scaling, then lets treatment effects vary by traffic context where the model supports it.</li>
</ul>
<p><span class="math display">\[
\text{Crash Risk} = \textbf{Baseline Propensity} \times \textbf{Traffic Scaling Behavior}
\]</span></p>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="cmf_technical_slides_clean - new_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="cmf_technical_slides_clean - new_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="cmf_technical_slides_clean - new_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="cmf_technical_slides_clean - new_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="cmf_technical_slides_clean - new_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="cmf_technical_slides_clean - new_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="cmf_technical_slides_clean - new_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="cmf_technical_slides_clean - new_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="cmf_technical_slides_clean - new_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="cmf_technical_slides_clean - new_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1200,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>